name: Espacio
email: kbellioum@itknowledgema.com
description: > #ESPACIO assure l’accompagne­ment et la concrétisation de vos projets d’aménagement, quel que soit l’am­pleur des chantiers.
baseurl: ""
url: "http://espaciomaroc.ma"

# Cloudinary assets
logo: https://res.cloudinary.com/unik/image/upload/v1487714904/projects/espacio/logo.png

# Build settings
markdown: kramdown
highlighter: rouge
sass:
  sass_dir: /assets/styles
  style: compressed

gems:
  - jekyll-sitemap
  - jekyll-redirect-from

exclude: ['Rakefile', 'config.ru', 'Gemfile', 'Gemfile.lock', 'vendor', 'bin']

port:    4001
