name: Espacio
email: ahlan@barmej.com
description: > #ESPACIO assure l’accompagne­ment et la concrétisation de vos projets d’aménagement, quel que soit l’am­pleur des chantiers.
baseurl: ""
url: "http://espaciomaroc.ma"

# Build settings
markdown: kramdown
highlighter: rouge
sass:
  sass_dir: /assets/styles
  style: compressed

gems:
  - jekyll-sitemap
  - jekyll-redirect-from

exclude: ['Rakefile', 'config.ru', 'Gemfile', 'Gemfile.lock', 'vendor', 'bin']